server.port=8094

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:store
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

#Soporte de resilience4j
resilience4j.circuitbreaker.instances.productoServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.productoServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.productoServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.productoServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productoServiceCB.wait-duration-in-open-state=3m
resilience4j.circuitbreaker.instances.productoServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.productoServiceCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.productoServiceCB.max-wait-duration-in-half-open-state=10s
resilience4j.timelimiter.instances.productoServiceCB.timeout-duration=3s
